# Generated by Django 5.0.6 on 2024-06-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=50)),
                ('domitorios', models.IntegerField()),
                ('metros_cuadrados', models.IntegerField()),
            ],
        ),
    ]
